# Engineering-Related Packages

Some R/DSP-related articles and books:

* [FIR Filter-Design and Digital-Signal Processing in R](https://www.r-bloggers.com/fir-filter-design-and-digital-signal-processing-in-r/) (https://www.r-bloggers.com/fir-filter-design-and-digital-signal-processing-in-r/)
* [R and Signal-Processing](http://blog.revolutionanalytics.com/2013/10/r-and-signal-processing.html) (http://blog.revolutionanalytics.com/2013/10/r-and-signal-processing.html)
* [Three ways to use MATLAB from R](https://mandymejia.wordpress.com/2014/08/18/three-ways-to-use-matlab-from-r/) (https://mandymejia.wordpress.com/2014/08/18/three-ways-to-use-matlab-from-r/), 
* [R for MATLAB users](http://mathesaurus.sourceforge.net/octave-r.html) (http://mathesaurus.sourceforge.net/octave-r.html), 
* [MATLAB vs R (from a MathWorks perspective)](http://www.mathworks.com/discovery/matlab-vs-r.html) (http://www.mathworks.com/discovery/matlab-vs-r.html)
* [What can MATLAB do that R cannot do (c. ~2012)](http://stackoverflow.com/questions/1738087/what-can-matlab-do-that-r-cannot-do) (http://stackoverflow.com/questions/1738087/what-can-matlab-do-that-r-cannot-do)
*  [Numerical Analysis and Statistics: MATLAB, R, NumPy (Python), Julia -- a side-by-side reference sheet](http://hyperpolyglot.org/numerical-analysis) (http://hyperpolyglot.org/numerical-analysis)
* book: [_R and MATLAB_](http://proquest.safaribooksonline.com/9781466568396), David Hiebeler
* chapter: "Essential Comparisons of the MATLAB and R Languages", within [_Functional Data Analysis with R and MATLAB_](http://link.springer.com/chapter/10.1007/978-0-387-98185-7_2)


* Of particular interest, might include some from the following [Task-Views](https://cran.r-project.org/web/views/) (http://www.rdocumentation.org/taskviews or http://www.maths.lancs.ac.uk/~rowlings/R/TaskViews/) packages such as the following:
    * "base-R" (arithmetic, input/ output, basic programming-support, e.g. `abs`, `all`, `all.equal`, `any`, `append`, `apply`, `Arg`/ `Mod`/ `Conj`, `array`, `asin`/ `acos`/ `atan`/ `atan2`, `attach`, `attr`, `backsolve`, `besselI`, `beta`, `bitwAnd`/ `bitwOr`/ `bitwNot`/ `bitwXor`, `bitwShiftL`/ `bitwShiftR`, `break`, **`c`**, `cat`/ `print`, `cbind`/ `rbind`, `ceiling`, `charmatch`, `chol`, `chol2inv`, `choose`, `colMeans`, `colnames`, `colSums`, `crossprod`, `cumsum`, `data.frame`, `detach`, `determinant`, `diag`, `dim`, `dimnames`, `dir`, `dirname`, `eigen`, `exists`, `exp`, `expand.grid`, `expression`, `factorial`, `file.append`, `file.copy`, `file.create`, `file.exists`, `file.info`, `file.path`, `file.remove`, `file.show`, `Find`, `floor`, `format`, `getwd`/`setwd`, `grep`, `gsub`, `hexmode`, `identical`, `identity`, `ifelse`, `Im`/ `Re`, `in`, `Inf`, `interactive`, `is.character`, `is.complex`, `is.element`, `is.numeric`, `jitter`, `kappa`, `kronecker`, `lapply`/ `mapply`/ `sapply`/ `tapply`, `length`, `LETTERS`, `library`, `list`, `list.files`, `log`/ `log10`/ `log2`, `ls`, `margin.table`, `match`, `matmult`, `matrix`, `max`, `mean`, `min`, `NA`/ `NaN`, `names`, `nchar`, `NCOL`, `norm`, `normalizePath`, `NROW`, `numeric`, `nzchar`, `options`, `order`, `outer`, **`paste`/ `paste0`**, `path.expand`, `pi`, `pmatch`, `pmax`, `pmin`, `polyroot`, `prettyNum`, `proc.time`, `qr`, `R.home`, `R.Version`, `range`, `rank`, `rcond`, `readChar`, `readLines`, `regexpr`, `rep`, `replace`, `require`, `rev`, `rm`, `round`, `row`, `row.names`, `rowMeans`, `rownames`, `rowsum`, `rowSums`, `sample`, `save`/ `load`, `scan`, `seq`, `set.seed`, `sign`, `signif`, `sin`/ `cos`/ `tan`, `sinpi`/ `cospi`/ `tanpi`, `solve`, `solve.qr`, `sort`, `source`, `sprintf`, `startsWith`, `stop`, `stopifnot`, `strrep`, `strsplit`, `strtoi`, `strtrim`, `sub`, `substr`, `sum`, **`summary`**, `svd`, `sweep`, `switch`, `Sys.Date`/ `Sys.time`, `Sys.info`, `system`, `system.file`, `system.time`, `t`, `tempdir`, `tempfile`, `tolower`, `toString`, `toupper`, `trunc`, `tryCatch`, `unique`, `which`, `which.max`, `which.min`, `with`, `writeBin`, `writeChar`, `writeLines`, `xor`, `zapsmall`, and many hundreds more ...)
    * "base-stats" (e.g. `acf`, `acf2AR`, `aggregate`, `AIC`, `alias`, **`anova`**, **`aov`**, `approx`, `ar`, `arima`, `ARMAacf`, `ARMAtoMA`, `ave`, `bandwidth.kernel`, `bartlett.test`, `binom.test`, `biplot`, `Box.test`, `ccf`, `chisq.test`, `coef`, `coefficients`, `confint`, `constrOptim`, `contrasts`, **`convolve`**, `cooks.distance`, `cor`, `cor.test`, `cov`, `cpgram`, `cutree`, `cycle`, `dbinom`/ `dcauchy`/ `dchisq`/ `dexp`/ `dgamma`/ `dgeom`/ `dhyper`/ `dlnorm`/ `dmultinom`/ `dnorm`/ `dpois`/ `dt`/ `dunif`/ `dweibull`/ `dwilcox`, `decompose`, `deltat`, `dendrogram`, `density`, `deriv`, `deviance`, `diff.ts`, `dist`, `ecdf`, `effects`, `embed`, `estVar`, **`fft`**, **`filter`**, `fisher.test`, `fivenum`, `formula`, **`frequency`**, `ftable`, `gaussian`, `glm`, `hat`, `hclust`, `heatmap`, `influence.measures`, `integrate`, **`interaction.plot`**, `KalmanSmooth`, `kernel`, `kmeans`, `knots`, `kruskal.test`, **`ks.test`**, `ksmooth`, `lag.plot`, `lm`, `loess.smooth`, `loglin`, `lowess`, `mahalanobis`, `median`, `mvfft`, `numericDeriv`, `offset`, `oneway.test`, `optimise`/ `optimize`, `pacf`, `pairwise.t.test`, `pbinom`/ `pcauchy`/ **`pchisq`**/ `pexp`/ `pf`/ `pgeom`/ **`pnorm`**/ `ppois`/ `pt`/ `punif`/ `pweibull`/ `pwilcox`, `poisson`, `poisson.test`, `poly`, `polym`, `ppoints`, `predict`, `proj`, `prop.test`, `ptukey`, `qbeta`/ `qcauchy`/ `qchisq`/ `qexp`/ `qf`/ `qgeom`/ `qnorm`/ `qpois`/ `qqline`/ `qt`/ `qunif`/ `qweibull`/ `qwilcox`, `qqnorm`, **`qqplot`**, `quantile`, `rbeta`/ `rbinom`/ `rcauchy`/ `rchisq`/ `rexp`/ `rf`/ `rgeom`/ `rmultinom`/ **`rnorm`**/ `rpois`/ `rt`/ **`runif`**/ `rweibull`/ `rwilcox`/ `rWishart`, `reshape`, `residuals`, `runmed`, `scatter.smooth`, `sd`, `shapiro.test`, `sigma`, `simulate`, `smooth`, `smooth.spline`, **`spec`**, **`spectrum`**, `spline`, **`t.test`**, `toeplitz`, `TukeyHSD`, **`uniroot`**, `var`, `var.test`, `wilcox.test`, `xtabs`, and many/ hundreds more ...),
    * **base-graphics** (e.g. **`abline`**, `arrows`, `axis`, `axTicks`, **`barplot`**, `box`, `boxplot`, `contour`, `coplot`, `curve`, `dotchart`, `filled.contour`, `fourfoldplot`, `frame`, `grid`, **`hist`**, `identify`, `image`, `layout`, `lcm`, `legend`, **`lines`**, `locator`, `matlines`, `matplot`, `pairs`, `panel.smooth`, `par`, `persp`, `pie`, **`plot`**, `points`, `polygon`, `polypath`, `rasterImage`, `rect`, `rug`, `screen`, `segments`, `smoothScatter`, `spineplot`, `split.screen`, `stars`, `stem`, `stripchart`, `sunflowerplot`, `symbols(circles=`...`)`, **`text`**, `xspline`, and dozens more ...)
    * grDevices (e.g. `axisTicks`, `bmp`, `cairo_pdf`, `col2rgb`, `colorRamp`, `colors`/ `colours`, `dev.new`, `getGraphicsEvent`, `gray`/ `grey`, `heat.colors`, `jpeg`, `msgWindow`, `palette`, `pdf`, **`png`**, `rainbow`, `rgb`, `terrain.colors`, `topo.colors`, `trans3d`, `windows`, and more ...)
        * also Mathematical-Annotation/ 'plotmath': (e.g. `sqrt`, `%prop%`, `plain`/ `bold`/ `italic`, `cdots`, `%subset%` / `%notsubset%`, `%in%` / `%notin%`, `hat`/ `tilde`/ `dot`/ `bar`/ `widehat`/ `widetilde`, **`alpha`--`omega`**, `infinity`, `partialdiff`, `nabla`, `degree`/ `minute`/ `second`, `displaystyle`/ `textstyle`/ `scriptstyle`, `underline`, `phantom`, `over`, **`frac`**, **`sum`**, **`integral`**, `lim`, and more ...)
    * utils (e.g. `available.packages`, `BATCH`, `bibentry`, `browseURL`, `capture.output`, `changedFiles`, `choose.dir`, `choose.files`, `citation`, `cite`, `clipboard`, `combn`, `count.fields`, `data`, `data.entry`, `debugger`, `demo`, `download.file`, `edit`, `emacs`, `example`, `file.edit`, `fileSnapshot`, `find`, **`head`/ `tail`**, `help`, `history`, `install.packages`, `memory.size`, `menu`, `object.size`, `person`, `personList`, `process.events`, `Rconsole`, **`read.table`**, `readClipboard`, `remove.packages`, `RHOME`, `Rprof`, `Rscript`, `RSiteSearch`, `rtags`, `savehistory`, `select.list`, `sessionInfo`, `setStatusBar`, `setWindowTitle`, `stack`, **`str`**, `summaryRprof`, `timestamp`, `txtProgressBar`, `type.convert`, `unstack`, `update.packages`, `vi`, `vignettes`, `winDialog`, `winMenuItems`, `winProgressBar`, `write.table`, and more ...)
    * [grid](https://www.stat.auckland.ac.nz/~paul/) (low-level graphics-system, [see Murrell book](https://www.stat.auckland.ac.nz/~paul/RG2e/), not avail from the CRAN repository -- since already part of "base" install now, e.g. `arcCurvature`, `arrow`, `bezierGrob`, `bezierPoints`, `circleGrob`, `clipGrob`, `curveGrob`, `dataViewport`, `frameGrob`, `functionGrob`, `grid.abline`, `grid.draw`, `grid.grep`, `grid.grill`, `grid.layout`, `grid.locator`, `grid.newpage`, `legendGrob`, `linesGrob`, `lineToGrob`, `moveToGrob`, `placeGrob`, `plotViewport`, `pointsGrob`, `polygonGrob`, `polylineGrob`, `rasterGrob`, `rectGrob`, `roundrect`, `segmentsGrob`, `showGrob`, `showViewport`, `textGrob`, `viewport`, `xaxisGrob`, `xsplineGrob`, `yaxisGrob`, and many more ...; see also package **`gridBase`**)

### Electrical-Engineering related

* Packages that might be useful to Engineers:
    * MATLAB-derived/ related:
        * **[signal](http://artax.karlin.mff.cuni.cz/r-help/library/signal/html/00Index.html)** ([original package](http://octave.sourceforge.net/signal/overview.html) was ported from [Octave](https://www.gnu.org/software/octave/)/ MATLAB: e.g. Filtering: [`filter`](http://rpackages.ianhowson.com/rforge/signal/man/filter.html), [`fftfilt`](http://rpackages.ianhowson.com/rforge/signal/man/fftfilt.html), `filtfilt`, `medfilt1`, `sgolay`, `sgolayfilt`; Resampling: `interp`, `resample`, `decimate`; IIR filter-design: `bilinear`, `butter`, `buttord`, `cheb1ord`, `cheb2ord`, `cheby1`, `cheby2`, `ellip`, `ellipord`, `sftrans`; FIR filter-design: [`fir1`](http://rpackages.ianhowson.com/rforge/signal/man/fir1.html), `fir2`, `remez`, `kaiserord`, `spencer`; Interpolation: `interp1`, `pchip`; Compatibility-routines/ utilities: `ifft`, `sinc`, `postpad`, `chirp`, `poly`, `polyval`; Windowing: `bartlett`, `blackman`, `boxcar`, `flattopwin`, `gausswin`, `hamming`, `hanning`, `triang`; Analysis and visualization: `freqs`, **[`freqz`](http://rpackages.ianhowson.com/rforge/signal/man/freqz.html)**, **`impz`**, **[`zplane`](http://rpackages.ianhowson.com/rforge/signal/man/zplane.html)**, **`grpdelay`**, **[`specgram`](http://octave.sourceforge.net/signal/function/specgram.html)**; System-/ Filter-Models: `Zpg`, `Arma`, `Ma`, and more),
        * **[pracma](https://octave.sourceforge.io/signal/index.html)** (i.e. ported from [Octave](https://www.gnu.org/software/octave/)/ MATLAB: `angle`, `arclength`, `arrayfun`, `bernoulli`, `bisect`, `bits`, `blanks`, `bsxfun`, `bubbleSort`, `bvp`, `cart2pol`, `cart2sph`, `cd`, `ceil`, `charpoly`, `chebApprox`, `chebCoeff`, `chebPoly`, `circlefit`, `circshift`, `clear`, `combs`, `compan`, `complexstep`, `cond`, **`conv`**, `cross`, `cubicspline`, `curvefit`, `cutpoints`, `dblquad`, `deblank`, `deconv`, `deg2rad`, `detrend`, `deval`, `Diag`, `direct1d`, `disp`, `distmat`, `dot`, `eig`, `ellipj`, `eps`, `erf`, `errorbar`, `eta`, `expint`, `expm`, `eye`, `ezcontour`, `ezmesh`, `ezplot`, `ezpolar`, `fact`, `factorial2`, `factors`, `fderiv`, **`fftshift`**, `fibsearch`, `findmins`, `findpeaks`, `finds`, `findstr`, `findzeros`, `Fix`, `flipdim`, `fliplr`/ `flipud`, `fminsearch`, `fnorm`, `fplot`, `fractalcurve`, `fresnelC`, `fsolve`, `fzero`, `fzsolve`, `gcd`, `geomean`, `givens`, `gmres`, `grad`, `gradient`, `gramSchmidt`, `hadamard`, `harmmean`, `heapSort`, `hessian`, `hilb`, `histc`, `householder`, `humps`, `hypot`, `idivide`, **`ifft`**, **`ifftshift`**, `Imag`, `insertionSort`, `integral`, `isempty`, `isprime`, `itersolve`, `jacobian`, `kron`, `laguerre`, `laplacian`, `Lcm`, `li`, `linprog`, `linspace`, `logit`, `loglog`, `logm`, `logseq`, `logspace`, `lu`, `magic`, `mergeSort`, `meshgrid`, `midpoint`, `mod`, `Mode`, `movavg`, `nchoosek`, `ndims`, `newton`, `nextpow2`, `Norm`, `normest`, `nthroot`, `null`, `nullspace`, `num2str`, `numderiv`, `numdiff`, `numel`, `ode23`, `ones`, `orth`, `pade`, `pascal`, `pdist`, `peaks`, `perms`, `piecewise`, `pinv`, `plotyy`, `pol2cart`, `polar`, `Poly`, `poly2str`, `pow2`, `ppfit`, `ppval`, `primes`, `psi`, `pwd`, `qrSolve`, `quad`, `quadprog`, `quadv`, `quickSort`, `quickSortx`, `quiver`, `rad2deg`, `rand`, `randcomb`, `randi`, `randn`, `randp`, `randperm`, `rands`, `randsample`, `Rank`, `rat`, `rationalfit`, `rats`, `Real`, `rectint`, `regexp`, `rem`, `repmat`, `Reshape`, `rmserr`, `rootm`, `roots`, `rortho`, `rot90`, `rref`, `runge`, `selectionSort`, `semilogx`, `semilogy`, `shellSort`, `sigmoid`, `signm`, `sinc`, `size`, `sortrows`, `sph2cart`, `sqrtm`, `squareform`, `std`, `std_err`, `steep_descent`, `str2num`, `strcat`, `strcmp`, `strfind`, `strRep`, `strTrim`, `subspace`, `taylor`, **`tic`/ `toc`**, `Toeplitz`, `Trace`, `trapz`, `trigApprox`, `trigPoly`, `tril`, `trimmean`, `triplequad`, `triquad`, `trisolve`, `triu`, `uniq`, `vander`, `vectorfield`, `ver`, `what`, `who`, `whos`, `wilkinson`, `zeros`, `zeta`, and many/ hundreds more ...),
        * **[matlab](http://rpackages.ianhowson.com/cran/matlab/)** (emulation code, smaller subset as from the **`pracma`** package above, but some additional functions that are unique to this package include: [**`imagesc`**](http://rpackages.ianhowson.com/cran/matlab/man/imagesc.html), `jet.colors`, `padarray`, `colorbar`, `fileparts`, `fullfile` (same as `base::file.path`), `find` (same as `base::which`), `cell` (same as `base::list`), and more ...),
        * **[matlabr](http://rpackages.ianhowson.com/cran/matlabr/)** ([no server needed here](https://www.r-bloggers.com/matlabr-a-package-to-calling-matlab-from-r-with-system/), e.g. [`run_matlab_script`](http://rpackages.ianhowson.com/cran/matlabr/man/run_matlab_script.html), [`run_matlab_code`](http://rpackages.ianhowson.com/cran/matlabr/man/run_matlab_code.html)),
        * **[R.matlab](http://rpackages.ianhowson.com/cran/R.matlab/)** (uses [MATLAB-server for remote-operations](http://www1.maths.lth.se/help/R/R.matlab/); but no MATLAB-server is needed for the `.mat` binary data-file conversion-functions: `readMat`, `writeMat`; and more),
        * RcppOctave (i.e. C++ wrapper to [Octave](https://www.gnu.org/software/octave/)/ MATLAB, pass some variables)
    * **[fftwtools](https://github.com/krahim/fftwtools)** (from [FFTW library](http://www.fftw.org/), e.g. `fftw`, `fftw2d`, `mvfftw`)
    * **[fftw](http://crantastic.org/packages/fftw)** package (from [FFTW library](http://www.fftw.org/), e.g. `DCT`, `FFT`, `IDCT`, `IFFT`)
    * [wavethresh](http://artax.karlin.mff.cuni.cz/r-help/library/wavethresh/html/00Index.html) ([book _Wavelet methods in Statistics with R_](http://www.springer.com/978-0-387-75960-9), e.g. [`wd`](http://artax.karlin.mff.cuni.cz/r-help/library/wavethresh/html/wd.html), [`wr`](https://people.maths.bris.ac.uk/~wavethresh/help/wr.htm), `imwd`, `imwr`, `mwd`, `mwr`, `accessC`, `accessD`, `draw`, and more ...)
    * [wmtsa](http://rpackages.ianhowson.com/cran/wmtsa/) (wavelet-methods for time-series analysis, e.g. `reconstruct`, `wavCWT`, `wavCWTPeaks`, `wavDaubechies`, `wavDWT`, `wavGain`, `wavTransform`, `wavVar`, and more ...)
    * [waveslim](http://www.rdocumentation.org/packages/waveslim/versions/1.7.5) ([notes](http://earlglynn.github.io/RNotes/package/waveslim/index.html), [see Gencay book](http://wwwf.imperial.ac.uk/~bwhitche/book/), e.g. `dwt`, [`dwt.2d`](http://earlglynn.github.io/RNotes/package/waveslim/dwt-2d.html), [`mra`](http://rpackages.ianhowson.com/rforge/waveslim/man/mra.html), `my.acf`, **`per`**, and more ...)
    * [wavelets](http://rpackages.ianhowson.com/cran/wavelets/) (e.g. `dwt`, `idwt`, and more ...)
    * [waved](http://artax.karlin.mff.cuni.cz/r-help/library/waved/html/00Index.html) (i.e. `FWaveD`, `WaveD`)
    * [rwt](http://www.rdocumentation.org/packages/rwt/versions/1.0.0) (Rice Univ wavelet-transform, wrapper from [MATLAB wavelets package](http://dsp.rice.edu/software/rice-wavelet-toolbox), e.g. [`denoise`](http://www.rdocumentation.org/packages/rwt/versions/1.0.0/topics/denoise), [`mdwt`](http://www.rdocumentation.org/packages/rwt/versions/1.0.0/topics/mdwt), `midwt`, `daubcoeff`, more ...)
    * [biwavelet](https://github.com/tgouhier/biwavelet) (port of [MATLAB package](http://noc.ac.uk/using-science/crosswavelet-wavelet-coherence), e.g. [`wt`](http://rpackages.ianhowson.com/cran/biwavelet/man/wt.html))
    * [Rwave](http://rpackages.ianhowson.com/rforge/Rwave/) (Time-Frequency analysis, [example](http://jaysthesisblog.com/R/wavelets_intro.html), e.g. [`cwt`](http://rpackages.ianhowson.com/rforge/Rwave/man/cwt.html), more ...)
    * [dtt](http://crantastic.org/packages/dtt) (Discrete Cosine-Transform DCT, e.g. [`dct`](http://rpackages.ianhowson.com/cran/dtt/man/dtt.html), `mvdct`)
    * [emd](http://dasan.sejong.ac.kr/~dhkim/software_emd.html) (Empirical Mode Decomposition, [see article](https://www.r-bloggers.com/wheres-the-magic-emd-and-ssa-in-r/), e.g. `emd`, `emd2d`, `emddenoise`, `extractimf`, `extrema`, `hilbertspec`, `imageEMD`, `lena`, **`spectrogram`**)
    * Acoustic/ Sound-Signal Processing:
        * **[seewave](http://rug.mnhn.fr/seewave/)** (e.g. `acoustat`, `attenuation`, `autoc`, [`bwfilter`](http://rug.mnhn.fr/seewave/HTML/MAN/bwfilter.html), `ceps`, `combfilter`, `convSPL`, `crest`, `cutspec`, `dBscale`, `dBweight`, `deletew`, `dfreq`, `diffenv`, `diffspec`, `diffwave`, `drawfilter`, `duration`, `dynoscillo`, `dynspec`, `echo`, `env`, `fbands`, `fdoppler`, [`ffilter`](http://rug.mnhn.fr/seewave/HTML/MAN/ffilter.html), `field`, [`fir`](http://rug.mnhn.fr/seewave/HTML/MAN/fir.html), `fpeaks`, **[`ftwindow`](http://rug.mnhn.fr/seewave/HTML/MAN/ftwindow.html)**, `fund`, `ggspectro`, `hilbert`, `ifreq`, `istft`, `lfs`, `listen`, `localpeaks`, `logspec.dist`, `meandB`, `meanspec`, `melfilterbank`, `micsens`, `moredB`, `mutew`, `NDSI`, `noisew`, `notefreq`, `octaves`, **[`oscillo`](http://rug.mnhn.fr/seewave/HTML/MAN/oscillo.html)**, `phaseplot`, `playlist`, `preemphasis`, `pulsew`, `Q`, `resamp`, `rms`, `roughness`, `savewav`, `seedata`, `simspec`, `smoothw`, `songmeter`, `soundscapespec`, `spec`, `specprop`, **[`spectro`](http://rug.mnhn.fr/seewave/HTML/MAN/spectro.html)**, `squarefilter`, **`stft.ext`**, `synth`, `timer`, `wf`, `zcr`, and dozens more ...)
        * **[tuneR](http://rpackages.ianhowson.com/cran/tuneR/)** (e.g. `sine`, `sawtooth`, `square`, `readWave`, `readMP3`, `bind`, `channel`, `downsample`, `mono`, `stereo`, **[`play`](http://artax.karlin.mff.cuni.cz/r-help/library/tuneR/html/play.html)**, **`periodogram`**, [`FF`](http://artax.karlin.mff.cuni.cz/r-help/library/tuneR/html/FF.html), `setWavPlayer`, `melfcc`, and more ... )
        * [audio](https://rforge.net/audio/) (e.g. `load.wave`, `pause`, [`play`](https://rforge.net/doc/packages/audio/play.html), **[`record`](https://rforge.net/doc/packages/audio/record.html)**, `resume`, `rewind`, `save.wave`, `wait`)
        * [monitoR](http://rpackages.ianhowson.com/cran/monitoR/) (automated acoustic template-matching, template-construction, spectrogram-viewing/ annotation, direct MySQL database connectivity, useful for managing recorders deployed in-the-field, and/or reading survey-metadata from sound-files on various external storage-media, [see article](https://acousticanalysisinr.wordpress.com/2016/01/28/using-monitor-to-detect-songs-5/), [GitHub](https://github.com/cran/monitoR), [Univ. Vermont](https://www.uvm.edu/rsenr/vtcfwru/R/?Page=monitoR/monitoR.htm), [USGS](https://pubs.er.usgs.gov/publication/70173746), [see article](http://www.tandfonline.com/doi/abs/10.1080/09524622.2015.1133320?journalCode=tbio20), [see article](http://search.proquest.com/docview/1656497151), e.g. `batchBinMatch`, `batchCorMatch`, `bindEvents`, [`binMatch`](http://finzi.psych.upenn.edu/R/library/monitoR/html/templateMatching.html), `collapseClips`, `combineBinTemplates`, `combineCorTemplates`, `compareTemplates`, [`corMatch`](http://www.rdocumentation.org/packages/monitoR/versions/1.0.4/topics/templateMatching), `corTemplate-class`, `eventEval`, `findPeaks`, `getDetections`, `getPeaks`, `makeBinTemplate`, `makeCorTemplate`, `mp3Subsamp`, `readMP3`, `showPeaks`, `survey`, `templateCutoff`, `timeAlign`, `viewSpec`, and more ...)
        * [phonTools](http://www.santiagobarreda.com/rscripts.html) (Socio-Phonetics/ Phonology; e.g. Acoustic-Analysis/ Visualization: `fastacf`, `findformants`, **[`freqresponse`](http://www.santiagobarreda.com/rstuff/freqresponse/freqresponse.html)**, `lpc`, `pitchtrack`, **[`polezero`](http://www.santiagobarreda.com/rstuff/polezero/polezero.html)**, `powertrack`, `pwelch`, `snip`, `selectslice`, `spectralslice`, **[`spectrogram`](http://www.santiagobarreda.com/rstuff/spectrogram/spectrogram.html)**; Audio-Manipulation: `Ffilter`, **[`FIRfilter`](http://www.santiagobarreda.com/rstuff/FIRfilter/FIRfilter.html)**, **[`makeFIR`](http://www.santiagobarreda.com/rstuff/makeFIR/makeFIR.html)**, `preemphasis`, `resample`, `synthfilter`, `vowelsynth`; Stats/ Math: `hotelling.test`, `interpolate`, `ldboundary`, `ldclassify`, `rotate`, `reduce.fraction`, `rmvtnorm`; Miscellaneous: `loadtable`, `multiplot`, `ntypes`, `phasor`, `peakfind`, `sinc`, `sinusoid`, **[`windowfunc`](http://www.santiagobarreda.com/rstuff/windowfunc/windowfunc.html)**, `zeroes`, and more ...)
        * [warbleR](http://marceloarayasalas.weebly.com/acoustic-analysis-in-r.html) (Streamline Bioacoustic/ birdsong Analysis, [workflow](https://cran.r-project.org/web/packages/warbleR/vignettes/warbleR_workflow.html), e.g. `autodetec`, `coor.graph`, `dfDTW`, `dfts`, `ffDTW`, `ffts`, [`lspec`](http://rpackages.ianhowson.com/cran/warbleR/man/lspec.html), `manualoc`, `mp32wav`, `sig2noise`, `snrspecs`, **[`specan`](http://rpackages.ianhowson.com/cran/warbleR/man/specan.html)**, **[`specreator`](http://www.rdocumentation.org/packages/warbleR/versions/1.1.2/topics/specreator)**, `trackfreqs`, `wavdur`, `xcorr`, `xcorr.graph`, and more)
        * [sound](http://rpackages.ianhowson.com/cran/sound/) (e.g. `center`, `channels`, `cutSample`, `duration`, `left`/ `right`, `mirror`, `Noise`, `normalize`, `noSilence`, `nullSample`, `panorama`, `pitch`, [`play`](http://www.rdocumentation.org/packages/sound/versions/1.4.4/topics/play), `rate`, `reverse`, `sampleLength`, `Sawtooth`, `Silence`, `Sine`, `Square`, `stereo`, and more ...)
    * Image-Processing:
        * **[ripa](http://rpackages.ianhowson.com/cran/ripa/man/RIPA-package.html)** (R image-processing and analysis, [see Frery book](http://www.springer.com/us/book/9781447149491); e.g. `clipping`, `contrast`, **[`fftImg`](http://rpackages.ianhowson.com/cran/ripa/man/fftImg.html)**, **[`fftw`](http://www.rdocumentation.org/packages/ripa/versions/2.0-2/topics/fftw)**, `highpass`, `lband`, `limage`, `loadBand`, `loadBandSample`, `lowpass`, `lscene`, `medianImg`, `modalDialog`, `normalize`, `RGB`, `rgb2grey`, `stretchImg`, `takeSamples`, `wband`, `zoom`, and more)
        * [imager](http://rpackages.ianhowson.com/cran/imager/) (uses [CImg library](http://cimg.eu/), e.g. `add.colour`, `autocrop`, `average`, `boxblur`, `bucketfill`, `capture.plot`, `center.stencil`, `channels`, [`convolve`](http://rpackages.ianhowson.com/cran/imager/man/convolve.html), `correlate`, `crop.borders`, `dilate`, `displacement`, [`display`](http://www.rdocumentation.org/packages/imager/versions/0.20/topics/display), [`display_list`](http://www.rdocumentation.org/packages/imager/versions/0.20/topics/display_list), `erode`, **[`FFT`](http://rpackages.ianhowson.com/cran/imager/man/FFT.html)**, `frames`, `grayscale`, `haar`, `imdirac`, [`imdraw`](http://rpackages.ianhowson.com/cran/imager/man/imdraw.html), `imfill`, `imgradient`, `imhessian`, `imnoise`, `imresize`, `imrotate`, `imsharpen`, `imshift`, `imsplit`, `imsub`, `imwarp`, `interp`, `isoblur`, `label`, [`load.image`](http://rpackages.ianhowson.com/cran/imager/man/load.image.html), `medianblur`, `mirror`, `mult`, `pad`, `parmax`/ `parmin`, `resize`, `stencil.cross`, `subim`, `threshold`, `warp`, `watershed`, and more ...)
        * [EBImage](http://earlglynn.github.io/RNotes/package/EBImage/Intro-to-EBImage.html) (European Bioinformatics Institute, uses [`ImageMagick`](https://www.imagemagick.org/), e.g. Spatial-transforms: `resize`, `flip`, `flop`, `transpose`, `rotate`, `translate`, `affine`, Image-segmentation/ object-manipulation: `thresh`, `bwlabel`, `otsu`, `watershed`, `propagate`, `ocontour`, `paintObjects`, `rmObjects`, `reenumerate`, Image-enhancement: `normalize`, `filter2`, `gblur`, `medianFilter`, Morphological-operations: [`makeBrush`](http://www.rdocumentation.org/packages/EBImage/versions/4.14.2/topics/morphology), `erode`, `dilate`, `opening`, `closing`, `distmap`, `floodFill`, `fillHull`, Colorspace-manipulation: `rgbImage`, `channel`, `toRGB`, Image-stacking/ combining/ tiling: `stackObjects`, `combine`, `tile`, `untile`, Draw on images: [`drawCircle`](http://rpackages.ianhowson.com/bioc/EBImage/man/drawCircle.html), Features-extraction: `computeFeatures`, and more)
        * [magick](https://github.com/ropensci/magick) (uses [ImageMagick](https://www.imagemagick.org/), e.g. Image-Transformations: `image_`... ...`trim`, ...`background`, ...`crop`, ...`scale`, ...`sample`, ...`border`, ...`noise`, ...`blur`, ...`edge`, ...`enhance`, ...`equalize`, ...`flip`, ...`flop`, ...`frame`, ...`negate`, ...`normalize`, ...`rotate`, ...`fill`, ...`chop`, ...`colorize`, ...`page`, ...`composite`, ...`contrast`, ...`annotate`; Image-Editing: `image_`... ...`browse`, ...`append`, ...`average`, ...`coalesce`, ...`flatten`, **...`fft`**, ...`map`, ...`montage`, ...`morph`, ...`mosaic`, ...`join`, ...`info`, ...`animate`, and more)
        * [jpeg](http://rpackages.ianhowson.com/cran/jpeg/) (e.g. [`readJPEG`](https://www.rforge.net/doc/packages/jpeg/readJPEG.html), more ...)
        * [png](http://rpackages.ianhowson.com/cran/png/) (e.g. [`readPNG`](https://www.rforge.net/doc/packages/png/readPNG.html), more ...)
    * Discrete-Event/ Queueing Simulation Packages:
        * [queueing](http://rpackages.ianhowson.com/cran/queueing/), [simmer](http://r-simmer.org/), [PDQ](http://www.perfdynamics.com/Tools/PDQcode.html), [omnetpp](https://github.com/omnetpp/omnetpp-resultfiles/tree/master/R-package), [SpaDES](http://spades.predictiveecology.org/), [spuRs](http://rpackages.ianhowson.com/cran/spuRs/), [markovchain](https://github.com/spedygiorgio/markovchain/), and more ...
        * [Simulation for Data-Science with R](https://qualityandinnovation.com/2015/07/28/simulation-for-data-science-with-r/)
    * Pattern-Recognition/ Data-Mining/ Predictive-Modelling: see Machine-Learning task-view, Cluster task-view, Time-Series task-view, Multi-variate task-view, Social-Sciences task-view at https://cran.r-project.org/web/views.

* **[Graphics-Related Task-View](https://cran.r-project.org/web/views/Graphics.html)** (~950K Downloads per month)
    * ade4, **animation**, ape, aplpack, ash, biclust, cairoDevice, cba, **colorspace**, diagram, dichromat, gclus, **ggplot2**, gplots, gridBase, hexbin, IDPmisc, igraph, iplots, JavaGD, klaR, **lattice**, latticeExtra, misc3d, onion, playwith, plotrix, **RColorBrewer**, rggobi, **rgl**, RGraphics, RGtk2, RSvgDevice, RSVGTipsDevice, scagnostics, scatterplot3d, seriation, tkrplot, vcd, vioplot, xgobi, and more ...

* **[Numerical-Mathematics Task-View](https://cran.r-project.org/web/views/NumericalMathematics.html)** (~660K Downloads per month)
    * in addition to above, some other Numerical-Mathematics packages: akima, appell, Bessel, combinat, conicfit, contfrac, cubature, Deriv, eigeninv, elliptic, expm, fastGHQuad, features, gaussquad, geigen, gmp, gsl, hypergeo, irlba, ktsolve, lamW, madness, magic, MASS, Matrix, matrixcalc, MonoPoly, mpoly, multipol, mvQuad, nleqslv, numbers, numDeriv, onion, optR, orthopolynom, Pade, partitions, permutations, polyCub, polynom, PolynomF, QZ, R2Cuba, rARPACK, Rmpfr, RootsExtremaInflections, **rPython**, Rserve, rSymPy, Ryacas, SparseGrid, SparseM, ssvd, statmod, stinepack, svd, and more ...

* **[Time-Series Task-View](https://cran.r-project.org/web/views/TimeSeries.html)** (~565K Downloads per month)
    * acp, AER, ArDec, arfima, astsa, autovarCore, BAYSTAR, bentcableAR, bfast, biwavelet, BNPTSclust, boot, BootPR, brainwaver, bspec, bsts, CADFtest, carx, cents, changepoint, chron, CommonTrend, costat, cts, depmix, depmixS4, deseasonalize, dlm, dlmodeler, dlnm, dse, **dtw**, dtwclust, dygraphs, dyn, dynlm, earlywarnings, Ecdat, ecp, EMD, ensembleBMA, EvalEst, events, expsmooth, fame, fanplot, fArma, FeedbackTS, fGarch, FGN, FinTS, FitAR, FitARMA, FKF, fma, fNonlinear, ForeCA, forecast, ForecastCombinations, forecTheta, fpp, fracdiff, fractal, fractalrock, fts, fUnitRoots, glarma, GMDH, gsarima, gtop, HarmonicRegression, hht, hts, hwwntest, imputeTS, its, jmotif, KFAS, KFKSDS, kza, locits, lomb, LPStimeSeries, LSTS, ltsa, lubridate, M4comp, MAPA, mAr, MAR1, mar1s, MARSS, Mcomp, meboot, mFilter, mlVAR, mondate, MSBVAR, MSwM, MTS, multitaper, mvcwt, nets, nlts, nonlinearTseries, npst, orderedLasso, paleoTS, partsm, pastecs, PCA4TS, pdfetch, pear, perARMA, pomp, portes, **psd**, ptw, Quandl, quantspec, rdatamarket, RGENERATE, Rlibeemd, rmaf, RMAWGEN, robfilter, RSEIS, Rssa, rts, rugarch, sae2, SDD, sde, seas, season, seasonal, Sim.DiffProc, sleekts, spTimer, stlplus, stochvol, strucchange, stsm, stsm.class, surveillance, TED, tempdisagg, tframe, Tides, tiger, timeDate, TimeProjection, timesboot, timeSeries, timsac, tis, tpr, trend, TSA, tsbugs, TSclust, tscount, TSdbi, TSdist, tsDyn, tseries, tseriesChaos, tseriesEntropy, tsfa, tsintermittent, TSMining, tsModel, tsoutliers, tsPI, TSTutorial, urca, VAR.etp, vars, VARsignR, Wats, wbsts, WeightedPortTest, wq, x12, x12GUI, xts, yuima, ZIM, zoo, ZRA, and more ...

* **[Optimization Task-View](https://cran.r-project.org/web/views/Optimization.html)** (~430K Downloads per month)
    * adagio, alabama, BB, boot, bvls, cccp, cec2005benchmark, cec2013, CEoptim, clpAPI, CLSOCP, clue, cmaes, cmaesr, copulaedas, cplexAPI, crs, dclone, DEoptim, DEoptimR, desirability, dfoptim, ECOSolveR, GA, genalg, GenSA, globalOptTests, glpkAPI, goalprog, GrassmannOptim, gsl, hydroPSO, igraph, irace, isotone, kernlab, kofnGA, lbfgs, lbfgsb3, limSolve, linprog, localsolver, LowRankQP, **lpSolve**, lpSolveAPI, matchingMarkets, matchingR, maxLik, mcga, mco, minpack.lm, minqa, neldermead, NlcOptim, nleqslv, nlmrt, nloptr, nls2, NMOF, nnls, onls, optimx, optmatch, parma, powell, pso, psoptim, qap, quadprog, quantreg, rcdd, RCEIM, Rcgmin, rCMA, Rcplex, Rcsdp, Rdsdp, rgenoud, Rglpk, rLindo, Rmalschains, Rmosek, rneos, ROI, Rsolnp, **Rsymphony**, Rvmmin, scs, smoof, sna, soma, subplex, tabuSearch, trust, trustOptim, TSP, ucminf

***

### Workflow-Related

See https://cran.r-project.org/web/views/

* **[Web-Technologies Task-View](https://cran.r-project.org/web/views/WebTechnologies.html)** (**~1.3M Downloads per month**)
    * aRxiv, AzureML, backblazer, bigml, bigrquery, boilerpipeR, boxr, captr, clarifai, colourlovers, curl, cymruservices, d3Network, datamart, ddeploy, discgolf, downloader, dvn, factualR, FastRWeb, fbRads, fitbitScraper, fitcoach, ggmap, ggvis, gistr, git2r, gitlabr, gmailr, googlesheets, **googleVis**, graphTweets, gsheet, httpcache, httping, httpRequest, httpuv, httr, imguR, instaR, jSonarR, jsonlite, jug, leafletR, livechatR, longurl, lucr, magrittr, mailR, mime, MTurkR, oai, OAIHarvester, opencpu, osmar, osrm, pdftables, plotGoogleMaps, plotKML, plusser, pubmed.mineR, pushoverr, randNames, rapport, Rbitcoin, Rblpapi, RCryptsy, **RCurl**, RDataCanvas, RefManageR, repmis, request, restimizeapi, Rexperigen, rfigshare, RForcecom, RGA, rgeolocate, RgoogleMaps, rio, rjson, RJSONIO, rLTP, Rmonkey, ROAuth, Rook, ROpenWeatherMap, rorcid, rplos, RPushbullet, rrefine, RSclient, rsdmx, RSelenium, Rserve, RSiteCatalyst, RSocrata, rvest, RYandexTranslate, RZabbix, scholar, scrapeR, searchConsoleR, sendmailR, servr, **shiny**, shopifyr, slackr, SocialMediaMineR, soql, streamR, tcltk, telegram, threewords, tidyjson, transcribeR, urltools, V8, webreadr, webshot, webutils, whisker, WikidataR, wikipediatrend, WikipediR, WufooR, XML, XML2R, yhatr, yummlyr, zendeskR, and more ...

* **[Reproducible-Research Task-View](https://cran.r-project.org/web/views/ReproducibleResearch.html)** (~828K Downloads per month)
    * **animation**, apaStyle, archivist, ascii, bibtex, brew, checkpoint, connect3, **DT**, formatR, formattable, highlight, highr, Hmisc, htmlTable, **htmltools**, HTMLUtils, humanFormat, hwriter, kfigr, Kmisc, **knitr**, lubridate, **markdown**, memisc, odfWeave, packrat, pander, papeR, prettyunits, quantreg, R2HTML, r2lh, R2PPT, R2wd, rapport, rbundler, RefManageR, **ReporteRs**, **reporttools**, resumer, **rmarkdown**, rms, rprintf, rtf, sparktex, stargazer, tables, TeachingSampling, texreg, tikzDevice, tth, tufterhandout, xtable, ztable, and more ...

* **[High-Performance Computing Task-View](https://cran.r-project.org/web/views/HighPerformanceComputing.html)** (~700K Downloads per month)
    * **Rcpp** (i.e. to run C++ subroutines and libraries),
    * **rJava** (i.e. to run Java subroutines and libraries),
    * prof, batch, BatchExperiments, BatchJobs, bayesm, bcp, biglars, biglm, bigmemory, bnlearn, caret, cudaBayesreg, data.table, dclone, doMC, doMPI, doRedis, doRNG, doSNOW, ff, ffbase, flowr, foreach, future, GAMBoost, gcbd, Geneland, gmatrix, gpuR, gputools, GUIProfiler, h2o, HadoopStreaming, harvestr, HiPLARM, HistogramTools, inline, LaF, latentnet, lga, Matching, MonetDB.R, nws, OpenCL, orloca, partDSA, pbdBASE, pbdDEMO, pbdDMAT, pbdMPI, pbdNCDF4, pbdPROF, pbdSLAP, peperr, PGICA, pls, pmclust, profr, proftools, pvclust, randomForestSRC, Rborist, Rdsm, rgenoud, Rhpc, RhpcBLASctl, RInside, rlecuyer, Rmpi, RProtoBuf, rredis, snow, snowfall, snowFT, speedglm, sprint, sqldf, STAR, tm, toaster, varSelRF, and more ...

***

### Other Statistical/ Data-Science Packages

See https://cran.r-project.org/web/views/

* **[Multi-variate Task-View](https://cran.r-project.org/web/views/Multivariate.html)** (~975K Downloads per month)
    * abind, ade4, amap, aplpack, ash, bayesm, ca, calibrate, car, caret, [class](https://stat.ethz.ch/R-manual/R-devel/library/class/html/00Index.html), clue, cluster, clusterGeneration, clusterSim, clustvarsel, clv, cocorresp, concor, copula, corpcor, covRobust, cramer, cwhmisc, delt, denpro, desirability, dr, e1071, earth, ellipse, energy, eRm, FactoMineR, FAiR, fastICA, feature, fgac, fpc, fso, gclus, GenKern, geometry, geozoo, gmodels, GPArotation, hddplot, Hmisc, homals, hybridHclust, ICS, ICSNP, iplots, JADE, kernlab, KernSmooth, kknn, klaR, knncat, kohonen, ks, **lattice**, ltm, mAr, MASS, Matrix, matrixcalc, **mclust**, MCMCpack, mda, mice, misc3d, mitools, mix, mnormt, MNP, monomvn, mvnmle, mvnormtest, mvoutlier, mvtnorm, nFactors, pan, paran, party, pcaPP, PearsonICA, pls, plsgenomics, poLCA, polycor, ppls, prim, proxy, psy, PTAk, rda, relaimpo, rggobi, **rgl**, robustbase, ROCR, rpart, rrcov, sca, **scatterplot3d**, sem, SensoMineR, seriation, simba, smatr, sn, spam, SparseM, SpatialNP, superpc, trimcluster, tsfa, vcd, vegan, VGAM, VIM, xgobi, YaleToolkit, and more ...

* **[Distributions Task-View](https://cran.r-project.org/web/views/Distributions.html)** (~325K Downloads per month)
    * actuar, ActuDistns, AdMit, agricolae, ald, AtelieR, bayesm, benchden, BiasedUrn, BivarP, bridgedist, CDVine, cmvnorm, CompGLM, CompLognormal, compoisson, Compounding, CompQuadForm, condMVNorm, copBasic, copula, csn, Davies, degreenet, Delaporte, denstrip, dirmult, disclap, DiscreteInverseWeibull, DiscreteLaplace, DiscreteWeibull, distr, distrDoc, distrEllipse, distrEx, DistributionUtils, distrMod, distrSim/ distrTeach/ distrTEst, e1071, emdbook, emg, EMMIXskew, EnvStats, evd, evdbayes, evir, ExtDist, FAdist, FatTailsR, fBasics, fCopulae, fExtremes, fgac, fitdistrplus, flexsurv, FMStable, fpow, frmqa, gambin, gamlss.dist, gamlss.mx, gaussDiff, gb, GB2, GenBinomApps, GeneralizedHyperbolic, GenOrd, geoR, ghyp, GIGrvg, gld, GLDEX, gldist, glogis, GMD, GSM, gumbel, HAC, hermite, HI, HistogramTools, HyperbolicDist, hyperdirichlet, ihs, JohnsonDistribution, kolmim, LambertW, LearnBayes, lhs, LIHNPSD, lmom, lmomco, Lmoments, logitnorm, loglognorm, MASS, mbbefd, mc2d, MCMCpack, mgpd, minimax, MitISEM, MixedTS, mixtools, MM, mnormpow, mnormt, modeest, moments, movMF, msm, mvprpb, mvrtn, mvtnorm, nCDunnett, Newdistns, nor1mix, NormalGamma, NormalLaplace, normalp, npde, ORDER2PARENT, OrdNor, ParetoPosStable, PDQutils, PearsonDS, PerMallows, PhaseType, poibin, poilog, poistweedie, polyaAeppli, poweRlaw, prob, qmap, randaes, random, randtoolbox, RDieHarder, reliaR, retimes, rlecuyer, RMKdiscrete, RMTstat, rstream, RTDE, rtdists, Runuran, s20x, sadists, SCI, setRNG, sfsmisc, sgt, skellam, SkewHyperbolic, skewt, sld, smoothmest, SMR, sn, sparseMVN, spd, stabledist, STAR, statmod, SuppDists, symmoments, tmvtnorm, tolerance, trapezoid, triangle, truncnorm, TSA, tsallisqexp, TTmoment, tweedie, VarianceGamma, VGAM, VineCopula, vines, zipfR

* [Machine-Learning Task-View](https://cran.r-project.org/web/views/MachineLearning.html) (~320K Downloads per month)
    * ahaz, arules, BayesTree, bigRR, bmrm, Boruta, bst, C50, caret, CORElearn, CoxBoost, Cubist, e1071, earth, elasticnet, ElemStatLearn, evtree, FCNN4R, frbs, GAMBoost, gamboostLSS, gbm, glmnet, glmpath, GMMBoost, grplasso, grpreg, h2o, hda, hdi, hdm, ipred, kernlab, klaR, lars, lasso2, LiblineaR, LogicForest, LogicReg, maptree, mboost, mlr, ncvreg, nnet, oblique.tree, pamr, party, partykit, penalized, penalizedLDA, penalizedSVM, quantregForest, randomForest, randomForestSRC, ranger, rattle, Rborist, rda, rdetools, REEMtree, relaxo, rgenoud, rgp, Rmalschains, rminer, ROCR, RoughSets, rpart, RPMM, RSNNS, RWeka, RXshrink, sda, SIS, stabs, SuperLearner, svmpath, tgp, tree, varSelRF, vcrpart

* [Bayesian Task-View](https://cran.r-project.org/web/views/Bayesian.html) (~315K Downloads per month)
    * abc, AdMit, arm, AtelieR, BaBooN, BACCO, BaM, BayesDA, bayesGARCH, bayesm, bayesmix, bayesQR, BayesSummaryStatLM, bayesSurv, Bayesthresh, BayesTree, BayesValidate, BayesX, BayHaz, BAYSTAR, bbemkr, BCBCSF, BCE, bclust, bcp, bfp, bisoreg, BLR, BMA, Bmix, BMS, bnlearn, boa, Bolstad, bqtl, bspec, bspmma, BSquare, BVS, catnet, coalescentMCMC, coda, cslogistic, cudaBayesreg, dclone, deal, dlm, DPpackage, EbayesThresh, ebdbNet, eco, eigenmodel, ensembleBMA, evdbayes, exactLoglinTest, factorQR, FME, geoR, geoRglm, ggmcmc, glmmBUGS, growcurves, hbsae, HI, Hmisc, iterLap, LearnBayes, lme4, lmm, MasterBayes, matchingMarkets, mcmc, MCMCglmm, MCMCpack, mgcv, mlogitBMA, MNP, mombf, monomvn, MSBVAR, pacbpred, PAWL, PottsUtils, predmixcor, PReMiuM, prevalence, profdpm, pscl, ramps, RJaCGH, rjags, RSGHB, rstan, rstiefel, runjags, Runuran, RxCEcolInf, SamplerCompare, SampleSizeMeans, SampleSizeProportions, sbgcop, SimpleTable, sna, spBayes, spikeslab, spikeSlabGAM, spTimer, stochvol, tgp, zic

* [Official-Statistics Task-View](https://cran.r-project.org/web/views/OfficialStatistics.html) (~270K Downloads per month)
    * Amelia, cat, CoImp, deducorrect, editrules, FFD, foreign, hbsae, Hmisc, hot.deck, IC2, ineq, JoSAE, laeken, lavaan, lavaan.survey, lme4, MatchIt, memisc, mi, mice, micEcon, MicSim, MImix, mipfp, missMDA, mitools, mix, nlme, norm, odfWeave, odfWeave.survey, pan, pps, prevR, pxR, questionr, RecordLinkage, reweight, robCompositions, rrcovNA, rsae, rworldmap, saeSim, sampling, samplingbook, SamplingStrata, samplingVarEst, SAScii, SDaA, sdcMicro, sdcTable, seasonal, SeleMix, simFrame, simPop, sms, spsurvey, StatMatch, stratification, stringdist, survey, synthpop, tabplot, TeachingSampling, tmap, treemap, vardpoor, VIM, x12, x12GUI, yaImpute

* **[Cluster-Analysis/ Finite-Mixture Task-View](https://cran.r-project.org/web/views/Cluster.html)** (~250K Downloads per month)
    * AdMit, amap, apcluster, BayesLCA, bayesm, bayesMCClust, bayesmix, bclust, bgmm, biclust, Bmix, cba, cclust, CHsharp, clue, cluster, clusterfly, clusterGeneration, clusterRepro, clusterSim, clustvarsel, clv, clValid, CoClust, compHclust, dbscan, dendextend, depmix, depmixS4, dpmixsim, dynamicTreeCut, e1071, EMCluster, evclust, FactoClass, fastcluster, fclust, FisherEM, flashClust, flexclust, flexCWM, flexmix, fpc, FunCluster, funFEM, funHDDC, gamlss.mx, genie, GLDEX, GSM, HDclassif, hybridHclust, isopam, kernlab, kml, latentnet, lcmm, longclust, mcclust, **mclust**, MetabolAnalyze, mixAK, mixdist, mixer, mixPHM, mixRasch, mixreg, MixSim, mixsmsn, mixtools, mixture, MOCCA, movMF, mritc, NbClust, nor1mix, optpart, ORIClust, pdfCluster, pendensity, pgmm, pmclust, poLCA, prabclus, PReMiuM, profdpm, protoclust, psychomix, pvclust, randomLCA, rjags, Rmixmod, RPMM, seriation, sigclust, skmeans, som, sparcl, tclust, teigen, treeClust, trimcluster, wle

* **[Experimental-Design (DoE) Task-View](https://cran.r-project.org/web/views/ExperimentalDesign.html)** (~28K Downloads per month)
    * agricolae, agridat, AlgDesign, ALTopt, asd, BatchExperiments, bcrm, BHH2, blocksdesign, blockTools, BsMD, conf.design, crossdes, Crossover, dae, daewr, designGG, desirability, DiceDesign, DiceEval, DiceKriging, DiceView, DoE.base, DoE.wrapper, DoseFinding, EngrExpt, experiment, FrF2, FrF2.catlg128, GAD, geospt, granova, gsbDesign, gsDesign, LDOD, lhs, MAMS, MaxPro, mixexp, mkssd, mxkssd, oapackage, OPDOE, OptGS, OptInterim, osDesign, pipe.design, planor, plgp, PopED, qtlDesign, RcmdrPlugin.DoE, rodd, rsm, SensoMineR, simrel, sp23design, support.CEs, TEQR, tgp, toxtestD, Vdgraph, VdgRsm

* **[Differential-Equations Task-View](https://cran.r-project.org/web/views/DifferentialEquations.html)** (~17K Downloads per month)
    * adaptivetau, bvpSolve, CollocInfer, deSolve, deTestSet, ecolMod, FME, GillespieSSA, mkin, nlmeODE, odeintr, PBSddesolve, PBSmodelling, pomp, **pracma**, primer, PSM, ReacTran, rootSolve, scaRabee, sde, simecol

* [Survival Task-View](https://cran.r-project.org/web/views/Survival.html) (~430K Downloads per month)
    * AER, aftgee, ahaz, AIM, asbio, aster, aster2, BaSTA, bayesSurv, BayHaz, BGPhazard, BMA, boot, bpcp, bshazard, bujar, censReg, clinfun, cmprsk, coarseDataTools, coin, compeir, compound.Cox, concreg, condGEE, CoxBoost, coxinterval, coxme, coxphf, coxphw, CoxRidge, coxrobust, CPE, CPHshape, Cprob, CR, crrSC, crrstep, currentSurvival, DAAG, dblcens, DPpackage, DStree, DTDA, dynpred, dynsurv, eha, emplik, Epi, epiR, etm, exactRankTests, fastcox, FHtest, fitdistrplus, flexsurv, frailtyHL, frailtypack, gamboostMSM, gamlss.cens, gbm, gems, genSurv, glmpath, globalboosttest, glrt, gof, gss, ICE, ICsurv, IDPSurvival, interval, invGauss, ipdmeta, ipred, JM, JMbayes, joineR, JPSurv, kaps, km.ci, kmc, kmconfband, kmi, KMsurv, lava.tobit, lbiassurv, LearnBayes, lmec, locfit, logconcens, LogicReg, LogrankA, logspline, lpc, lsmeans, lss, MAMSE, maxstat, mboost, MCMCglmm, MCMCpack, mets, mfp, MicSim, MIICD, mixAK, mixPHM, MLEcens, MRsurv, msm, msSurv, MST, mstate, muhaz, multcomp, multipleNCC, mvna, NADA, NestedCohort, NPHMC, NPMLEcmprsk, OIsurv, OrdFacReg, OutlierDC, p3state.msm, paf, pamr, parfm, party, pec, penalized, penMSM, peperr, PermAlgo, PHeval, phmm, plsRcox, polspline, powerSurvEpi, PReMiuM, prodlim, psbcGroup, pseudo, quantreg, randomForestSRC, rankhazard, relsurv, rhosp, riskRegression, risksetROC, rms, RobustAFT, ROCt, rpart, rsig, saws, SemiCompRisks, SemiMarkov, SGL, simexaft, simMSM, simPH, SMIR, SmoothHazard, smoothHR, smoothSurv, SMPracticals, spatstat, spatsurv, spBayesSurv, superpc, surv2sampleComp, survAccuracyMeasures, survAUC, survC1, survexp.fr, survey, Survgini, survIDINRI, survival, survivalMPL, survivalROC, survJamda, survPresmooth, survrec, survsim, survSNP, SvyNom, TBSSurvival, TestSurvRec, timereg, timeROC, tlmec, TPmsm, tpr, TraMineR, TSHRC, uniCox, VGAM, vitality, wtcrsk, YPmodel

* [Robust Statistical-Methods/ Design Task-View](https://cran.r-project.org/web/views/Robust.html) (~195K Downloads per month)
    * covRobust, coxrobust, distr, drgee, FRB, georob, GSE, lqmm, MASS, mblm, multinomRob, mvoutlier, OutlierDC, OutlierDM, quantreg, RandVar, rgam, roahd, RobAStBase, robcor, robeth, robfilter, RobLox, RobLoxBioC, RobPer, RobRex, RobRSVD, robumeta, robust, RobustAFT, robustbase, robustDA, robustgam, robustlmm, robustloggamma, robustreg, robustX, ROptEst, ROptRegTS, ror, rorutadis, rrcov, rrcovHD, rrcovNA, rsig, RSKC, sandwich, ssmrob, TEEReg, wle, WRS2

***

## Other Packages (e.g. Domain-Specific)

* [Clinical-Trials Task-View](https://cran.r-project.org/web/views/ClinicalTrials.html) (~210K Downloads per month)
    * adaptTest, AGSDest, asd, asypow, bcrm, bifactorial, binomSamSize, blockrand, clinfun, clinsig, coin, conf.design, CRM, CRTSize, dfcrm, DoseFinding, epibasix, experiment, FrF2, GroupSeq, gsDesign, HH, Hmisc, ldbounds, longpower, MChtest, MCPMod, meta, metafor, metaLik, metasens, multcomp, nppbib, PIPS, PowerTOST, pwr, PwrGSD, qtlDesign, rmeta, samplesize, seqmon, speff2trial, ssanv, survival, TEQR, TrialSize

* [ChemPhys Task-View](https://cran.r-project.org/web/views/ChemPhys.html) (~110K Downloads per month)
    * ALS, AnalyzeFMRI, AquaEnv, astro, astrodatR, astroFns, astrolibR, Bchron, BioMark, bvls, cda, celestial, CellularAutomaton, chemCal, chemometrics, ChemometricsWithR, ChemometricsWithRData, ChemoSpec, CHNOSZ, clustvarsel, compositions, cosmoFns, CosmoPhotoz, CRAC, dielectric, diffractometry, drc, drm, EEM, elasticnet, fastICA, FITSio, fmri, fpca, FTICRMS, homals, hyperSpec, investr, Iso, kohonen, leaps, lspls, MALDIquant, minpack.lm, moonsun, nlme, nlreg, nnls, OrgMassSpecR, pcaPP, Peaks, PET, planar, pls, plspm, ppls, prospectr, psy, PTAk, quantchem, rcdk, rcdklibs, represent, resemble, RobPer, rpubchem, sapa, SCEPtER, simecol, snapshot, solaR, som, speaq, spls, stellaR, stepPlr, subselect, TIMP, titan, titrationCurves, UPMASK, varSelRF, webchem, WilcoxCV

* [gRaphical Models Task-View](https://cran.r-project.org/web/views/gR.html) (~100K Downloads per month)
    * abn, bayesmix, BDgraph, bnlearn, boa, BRugs, catnet, coda, dclone, deal, diagram, dynamicGraph, ergm, FBFsearch, GeneNet, ggm, giRaph, gRain, gRapHD, gRbase, gRc, gRim, huge, igraph, mathgraph, ndtv, network, networkDynamic, parcor, pcalg, QUIC, R2OpenBUGS, R2WinBUGS, rbugs, rjags, SIN

* [Meta-Analysis Task-View](https://cran.r-project.org/web/views/MetaAnalysis.html) (~22K Downloads per month)
    * altmeta, bamdit, bayesmeta, bmeta, bspmma, CAMAN, compute.es, CopulaREMADA, CRTSize, dosresmeta, EasyStrata, ecoreg, epiR, etma, exactmeta, extfunnel, forestplot, gap, gemtc, gmeta, hetmeta, HSROC, ipdmeta, joint.Cox, MAc, MAd, mada, MAMA, MAVIS, meta, meta4diag, MetABEL, metacor, MetaDE, metafor, metagear, metagen, metaLik, metaMA, metamisc, metansue, metap, MetaPath, MetaPCA, metaplus, MetaQC, metaRNASeq, metaSEM, metasens, MetaSKAT, metatest, Metatron, mmeta, MultiMeta, mvmeta, mvtmeta, netmeta, pcnetmeta, psychometric, PubBias, RcmdrPlugin.EZR, RcmdrPlugin.RMTCJags, rmeta, robumeta, SAMURAI, SCMA, selectMeta, seqMeta, skatMeta, weightr, xmeta
